name: "tiny_pytorch test workflow"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: install self
        run: |
          poetry install
      - name: test with pytest
        run: |
          poetry run pytest
